"""add payments table

Revision ID: add_payments_table
Revises: b35335476dde
Create Date: 2025-12-24 12:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_payments_table'
down_revision: Union[str, None] = 'b35335476dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Dialect-agnostic types: JSONB on Postgres, JSON on SQLite; UUID on Postgres, String(36) on SQLite.
# Use Postgres for production; migrations still run with SQLite when DATABASE_URL is unset.
PAYMENT_METADATA_TYPE = postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite")
UUID_TYPE = postgresql.UUID(as_uuid=True).with_variant(sa.String(36), "sqlite")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('paypal_order_id', sa.String(length=100), nullable=False),
    sa.Column('paypal_capture_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_metadata', PAYMENT_METADATA_TYPE, nullable=True),
    sa.Column('user_id', UUID_TYPE, nullable=True),
    sa.Column('organization_id', UUID_TYPE, nullable=True),
    sa.Column('id', UUID_TYPE, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_capture_id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    op.create_index(op.f('ix_payments_paypal_order_id'), 'payments', ['paypal_order_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_paypal_order_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###

