import { Zap } from 'lucide-react';
import { Link } from 'react-router-dom';

const PRIVACY_TEXT = `Privacy Policy
Last Updated: 15-Dec-2025

ApexNeural Private Limited (“ApexNeural”, “we”, “us”, “our”) respects your privacy and is
committed to protecting your personal data. This Privacy Policy describes how we collect, use, store,
share, and protect your information in accordance with the Digital Personal Data Protection Act, 2023
(DPDP Act), the Information Technology Act, 2000, the Information Technology (Reasonable
Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 (SPDI
Rules), and other applicable laws.

This Privacy Policy applies to your use of this website, its related domains, subdomains, product-
specific websites, mobile applications, APIs, dashboards, AI or machine-learning tools, and any
related services operated by ApexNeural (collectively, the “Platform” or “Services”).
This website and all related product websites, domains, and subdomains are owned and operated by
ApexNeural Private Limited, unless explicitly stated otherwise.

1. Personal Data We Collect
1.1 Data Provided by You
When you use our Platform, you may voluntarily provide:
• Full name, email address, phone number, and company name
• Login or account registration details
• Billing and payment information (if you purchase paid plans)
• Files, text, documents, datasets, media or any content uploaded by you (“User Content”)

1.2 Data Collected Automatically
We automatically collect:
• IP address, device and browser type, operating system
• Usage metrics such as pages visited, actions performed, features used, session duration
• Cookies, pixel tags, web beacons and similar tracking technologies (See Section 10)

1.3 Data Generated by Our AI Services
• Inputs submitted to our AI systems
• Outputs generated by the Platform in response to your inputs
• Conversation history, customization preferences, and feedback

1.4 Definition of Personal Data
“Personal data” means any data relating to an identifiable individual. It does not include anonymized
or aggregated data that cannot identify you.

1.5 How This Website Collects, Uses, Stores, and Protects Data (Firecrawl Agent)
To operate Firecrawl Agent’s features (PDF upload, indexing, chat, and web search), we may process:
• Uploaded PDFs and extracted text/chunks to generate vector embeddings and enable retrieval.
• Your chat messages/queries and the generated outputs to provide responses and show history/logs.
• Session identifiers and basic metadata (e.g., upload time, file name, file size) to manage sessions.

Where data is stored (typical deployments):
• Account/authentication records are stored in our application database.
• Chat/session metadata may be stored in memory and/or the application database.
• Document embeddings and retrieval indexes may be stored in a vector database (e.g., ChromaDB),
  which persists on the server.
• Authentication tokens may be stored on your device (e.g., browser local storage) to keep you signed in.

Third-party processing:
• Web search requests may be sent to Firecrawl to retrieve web context.
• Your prompts and relevant retrieved context may be sent to the configured LLM provider (e.g., via
  OpenRouter/OpenAI/local LLM tooling) to generate responses.
• If you subscribe to updates, your email address is processed to send newsletters (e.g., via SendGrid).
• If you purchase a plan, payment details are handled by the payment processor (e.g., PayPal); we receive
  transaction/order identifiers and related status information.

Security safeguards:
• We use access controls and authentication to restrict access to accounts and services.
• Data is transmitted using encryption in transit (TLS/SSL where available).
• We apply reasonable security practices (e.g., least-privilege access, monitoring, and periodic review).
However, no system can be guaranteed 100% secure.

Deletion/retention:
• If you delete a session, we take reasonable steps to delete the session’s associated retrieval index from the
  server where supported by the deployment. Some operational logs and backups may persist for a limited
  period for security and compliance purposes.

2. Lawful Basis for Processing
Under the Digital Personal Data Protection Act, 2023 (DPDP Act) and other applicable laws, we
process personal data based on one or more of the following lawful grounds:
• your consent.
• performance of a contract or provision of requested Services.
• legitimate business purposes, including security, analytics, research, service improvement,
fraud prevention, and internal operations.
• compliance with legal or regulatory obligations.

3. User Responsibility for Uploaded Content
You are responsible for ensuring that any User Content, including documents, images, datasets, or
files uploaded to the Platform:
• does not infringe the privacy or rights of others,
• does not contain personal data of any individual without lawful authorization or consent.
Uploading sensitive or illegal content is strictly prohibited.

4. How We Use Your Data
We use personal data to:
• Provide, operate, maintain and improve our Services
• Personalize user experience and AI outputs
• Manage payments, billing, and account services
• Communicate with you (support, alerts, service updates, newsletters if you opt-in)
• Monitor usage patterns and enhance platform performance
• Detect, prevent, and mitigate fraud, abuse, or security threats
• Conduct research or analytics without identifying individuals
• Train, tune, evaluate, and improve artificial intelligence and machine-learning models
• Perform internal analytics, benchmarking, and business intelligence
• Develop new products, features, and services
• Comply with applicable laws, legal requests, or regulatory requirements

5. Use of Data for AI Training
5.1 By default, User Content, inputs, outputs, and interaction data may be used to train, tune, evaluate,
and improve our artificial intelligence and machine-learning models, unless you opt out where such
option is provided.
5.2 We take reasonable steps to avoid using data that directly identifies individuals for model training,
unless such use is permitted under applicable law or based on your consent.
5.3 You may opt out of training use anytime by:
• Using account settings, or
• Emailing info@apexneural.com with subject: “Opt-Out of Model Training”
5.4 Anonymized or aggregated data that cannot identify you may still be retained or used for
improvement.

6. Automated Decision-Making & Disclaimer
Our AI-powered systems may generate recommendations or insights based on your inputs.
No legally significant decisions are made solely through automated processing.
Outputs should not be treated as professional advice without independent human review.

7. Sharing & Disclosure of Personal Data
We do not sell personal data. We share data only with:
• Cloud hosting providers and data processors (with equivalent or higher protection obligations)
• Payment processors and fraud prevention partners
• Professional advisors, attorneys, auditors, or insurers where necessary
• Governmental or regulatory authorities if legally required
• Third parties in case of merger, acquisition, or business transfer (data will continue under this
Policy)
All third-party processors act only under our instructions and legal agreements.
We may also share anonymized or aggregated data that does not identify individuals for research,
analytics, business insights, or product improvement purposes.

8. International Transfers
Your data is primarily stored and processed in India. If transferred outside India, we ensure adequate
safeguards consistent with DPDP Act standards and applicable international requirements.

9. Data Security
We implement industry-standard organizational and technical controls, including:
• Encryption at rest (AES-256 where applicable)
• Encryption in transit (TLS/SSL)
• Access control and authentication procedures
• Regular vulnerability assessment and monitoring
However, no electronic transmission or storage method is 100% secure.

10. Cookies & Tracking Technologies
We use:
• Essential cookies (required for site functionality)
• Optional analytics cookies (e.g., Google Analytics / Plausible)
Optional cookies are used only with your consent. You may manage preferences via browser settings
or cookie banner.

11. Data Retention
We retain personal data for as long as reasonably necessary to fulfill the purposes described in this
Policy, including operational, analytical, research, development, security, compliance, and legal
purposes.
Category Retention Duration
Account data Until account deletion + up to 180 days
Billing & tax records 8 years (legal requirement)
Inputs/Outputs Until deleted by you or you opt-out
Logs & analytics Up to 12 months
Legal disputes/compliance As required for protection or claims
Anonymized or aggregated data that cannot reasonably identify an individual may be retained
indefinitely.

12. Your Rights Under DPDP Act
You have the right to:
• Access your personal data
• Request corrections or updating of inaccurate data
• Withdraw consent (where processing is consent-based)
• Request deletion (subject to legal exceptions)
• Nominate a person to exercise rights on your behalf in case of death/incapacity
• File a complaint with the Data Protection Board of India
To exercise rights, email: info@apexneural.com
Subject: “DPDP Rights Request”

13. Personal Data Breach Notification
In case of a personal data breach affecting your rights, we will notify:
• You (where required by law), and
• The Data Protection Board of India, in accordance with legal obligations.

14. Children’s Privacy
Our Services are not intended for individuals under 18 years of age. We do not knowingly collect data
from children. If inadvertently collected, we will delete it upon request.

15. Grievance Officer
Name: S.B.Rao
Designation: Grievance Officer
Email: grievance@apexneural.com
Phone: +91-98499 49597
Address:
ApexNeural Private Limited,
5th Floor, Shantha Sriram Building, PRS Towers,
Gachibowli, K.V. Rangareddy,
Telangana, India – 500032
• We will acknowledge grievances within 7 days
• We will aim to resolve them within 30 days

16. Updates to This Policy
We may update this Privacy Policy periodically. If material changes are made, we will notify you via
email or a prominent notice on the Platform. Continued use of the applicable Website or Services after
such updates constitutes acceptance of the revised Privacy Policy.

17. Contact Us
For privacy questions or concerns:
info@apexneural.com
Registered Address:
ApexNeural Private Limited
5th Floor, Shantha Sriram Building, PRS Towers,
Gachibowli, Telangana, India – 500032
CIN: U62013TS2024PTC189416
This Privacy Policy applies to all websites and platforms operated by ApexNeural unless a separate
privacy policy is explicitly provided.
`;

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#050505] text-white">
      <header className="border-b border-white/10 bg-black/40 backdrop-blur-xl">
        <div className="max-w-5xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-tr from-blue-600 to-indigo-600 rounded-lg flex items-center justify-center">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="text-lg font-bold tracking-tight">Firecrawl Agent</span>
          </Link>
          <Link to="/" className="text-sm text-gray-400 hover:text-white transition-colors">
            Back to Home
          </Link>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-10">
        <h1 className="text-3xl sm:text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-8">Last Updated: 15-Dec-2025</p>
        <div className="whitespace-pre-wrap text-sm leading-relaxed text-gray-300">
          {PRIVACY_TEXT}
        </div>
      </main>
    </div>
  );
}


