import { Link } from 'react-router-dom';
import { 
  FileText, Shield, Users, CreditCard, Scale, AlertTriangle, 
  Globe, Lock, Mail, Building2, ArrowLeft, Sparkles, BookOpen, Zap
} from 'lucide-react';

const sections = [
  {
    id: 'changes',
    title: '1. Changes to Terms',
    icon: FileText,
    color: 'from-blue-500 to-cyan-500',
    content: `We may revise these Terms at any time. Changes will be posted on the Platform, and the "Last Updated" date will be revised. Your continued use of the Platform following any update constitutes acceptance of the revised Terms. Your sole remedy if you do not agree with the revised Terms is to discontinue use of the Platform.`
  },
  {
    id: 'services',
    title: '2. Description of Services',
    icon: Sparkles,
    color: 'from-purple-500 to-pink-500',
    content: `ApexNeural provides the Firecrawl Agent platform, an agentic RAG (Retrieval‑Augmented Generation) application that combines document retrieval with real-time web search.

Depending on your configuration and plan, the Platform may allow you to:
• Create an account and authenticate to access the dashboard
• Upload PDF documents for parsing, chunking, embedding, and indexing
• Ask questions in a chat interface with AI-generated responses
• Trigger real-time web search via Firecrawl when needed
• View processing details/logs, manage sessions, and delete sessions
• Subscribe to product updates and purchase paid plans`
  },
  {
    id: 'eligibility',
    title: '3. Eligibility',
    icon: Users,
    color: 'from-green-500 to-emerald-500',
    content: `You must be at least 18 years old and legally capable of entering into binding contracts to use the Platform. By using the Services, you represent that you meet this requirement.`
  },
  {
    id: 'accounts',
    title: '4. User Accounts',
    icon: Lock,
    color: 'from-amber-500 to-orange-500',
    content: `You are responsible for maintaining the confidentiality of your login credentials and for activities occurring under your account. You must notify us immediately at info@apexneural.com of any unauthorized use. We are not responsible for any loss arising due to unauthorized access resulting from your failure to secure your account.`
  },
  {
    id: 'acceptable-use',
    title: '5. Acceptable Use',
    icon: Shield,
    color: 'from-red-500 to-rose-500',
    content: `You agree not to:
• Use the Services for any illegal, unauthorized, harmful, or unethical purpose
• Upload content that is defamatory, obscene, discriminatory, or harmful
• Use data without lawful rights or consents
• Use for high-risk activities without independent verification
• Probe, scan, or attempt to bypass security controls
• Crawl, scrape, or systematically copy data without consent
• Reverse-engineer or attempt to derive source code
• Resell or commercially exploit the Services without agreement
• Generate deepfakes or misleading content`
  },
  {
    id: 'content',
    title: '6. User Content & Outputs',
    icon: BookOpen,
    color: 'from-indigo-500 to-violet-500',
    content: `User Content: Any content you submit to the Platform. You retain ownership but grant ApexNeural a license to process it for service delivery and improvement.

Outputs: Content generated by the Services, licensed to you for personal or internal business use. Outputs may not be unique and ApexNeural does not guarantee accuracy. You are responsible for verifying accuracy and suitability.`
  },
  {
    id: 'ip',
    title: '7. Intellectual Property',
    icon: Scale,
    color: 'from-teal-500 to-cyan-500',
    content: `All rights, title, and interest in the Platform, Services, algorithms, models, trademarks, software, and technology belong exclusively to ApexNeural or licensors. No rights are granted except those expressly stated in these Terms.`
  },
  {
    id: 'payments',
    title: '8. Payments & Refunds',
    icon: CreditCard,
    color: 'from-emerald-500 to-green-500',
    content: `Certain features may be free; others may require payment. Taxes are additional unless expressly stated. Payments are non-refundable unless required by applicable law. In case of chargebacks or non-payment, ApexNeural may suspend access immediately.`
  },
  {
    id: 'disclaimer',
    title: '12. Disclaimer',
    icon: AlertTriangle,
    color: 'from-yellow-500 to-amber-500',
    content: `THE PLATFORM AND SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND. OUTPUTS DO NOT CONSTITUTE PROFESSIONAL ADVICE AND SHOULD NOT BE USED WITHOUT INDEPENDENT VERIFICATION.`
  },
  {
    id: 'liability',
    title: '13. Limitation of Liability',
    icon: Shield,
    color: 'from-slate-500 to-gray-500',
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, APEXNEURAL SHALL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES. TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE GREATER OF INR 30,000 OR FEES PAID IN THE 12 MONTHS PRECEDING THE CLAIM.`
  },
  {
    id: 'governing',
    title: '15. Governing Law',
    icon: Globe,
    color: 'from-blue-500 to-indigo-500',
    content: `These Terms are governed by the laws of India. Disputes shall first be attempted to be resolved amicably within 30 days. Failing resolution, disputes shall be referred to binding arbitration in Hyderabad, Telangana, under the Arbitration and Conciliation Act, 1996.`
  }
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#030303] text-white">
      {/* Animated background */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-purple-500/10 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '1s' }} />
        <div className="absolute top-1/2 left-1/2 w-64 h-64 bg-cyan-500/5 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '2s' }} />
      </div>

      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-white/10 bg-black/60 backdrop-blur-xl">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-3 group">
            <div className="w-10 h-10 bg-gradient-to-tr from-blue-600 to-indigo-600 rounded-xl flex items-center justify-center shadow-lg shadow-blue-500/25 group-hover:shadow-blue-500/40 transition-shadow">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="text-lg font-bold tracking-tight">Firecrawl Agent</span>
          </Link>
          <Link 
            to="/" 
            className="flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 text-sm text-gray-300 hover:text-white transition-all"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative py-16 sm:py-24">
        <div className="max-w-6xl mx-auto px-4 sm:px-6">
          <div className="text-center mb-12">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-sm mb-6">
              <FileText className="w-4 h-4" />
              Legal Document
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-4 bg-gradient-to-r from-white via-gray-200 to-gray-400 bg-clip-text text-transparent">
              Terms of Use
            </h1>
            <p className="text-gray-400 text-lg max-w-2xl mx-auto">
              Please read these terms carefully before using the Firecrawl Agent platform
            </p>
            <p className="text-sm text-gray-500 mt-4">Last Updated: 15-Dec-2025</p>
          </div>

          {/* Introduction Card */}
          <div className="relative rounded-3xl border border-white/10 bg-gradient-to-br from-white/[0.05] to-transparent p-8 mb-12 overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-blue-500/10 to-transparent rounded-full blur-2xl" />
            <div className="relative">
              <h2 className="text-xl font-semibold mb-4 flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center">
                  <BookOpen className="w-5 h-5" />
                </div>
                Introduction
              </h2>
              <p className="text-gray-300 leading-relaxed">
                These Terms of Use ("Terms") govern your access to and use of this website, its related domains, 
                subdomains, product-specific websites, mobile applications, APIs, dashboards, communications, and 
                any related products and services operated by <span className="text-white font-medium">ApexNeural Private Limited</span> ("ApexNeural", "we", "us", or "our").
              </p>
              <p className="text-gray-400 mt-4 text-sm">
                If you do not agree with these Terms or the applicable Privacy Policy, you must not access or use the Platform.
                Accessing the Platform with or without creating an account constitutes your acceptance of these Terms.
              </p>
            </div>
          </div>

          {/* Sections Grid */}
          <div className="grid gap-6 md:grid-cols-2">
            {sections.map((section, index) => {
              const Icon = section.icon;
              return (
                <div
                  key={section.id}
                  className="group relative rounded-2xl border border-white/10 bg-white/[0.02] hover:bg-white/[0.04] p-6 transition-all duration-300 hover:border-white/20"
                  style={{ animationDelay: `${index * 50}ms` }}
                >
                  <div className="flex items-start gap-4">
                    <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${section.color} flex items-center justify-center flex-shrink-0 shadow-lg`}>
                      <Icon className="w-6 h-6 text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="text-lg font-semibold text-white mb-3 group-hover:text-transparent group-hover:bg-gradient-to-r group-hover:from-white group-hover:to-gray-300 group-hover:bg-clip-text transition-all">
                        {section.title}
                      </h3>
                      <p className="text-sm text-gray-400 leading-relaxed whitespace-pre-line">
                        {section.content}
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Contact Section */}
          <div className="mt-12 rounded-3xl border border-white/10 bg-gradient-to-br from-orange-500/10 via-transparent to-red-500/10 p-8">
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-6">
              <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-orange-500 to-red-500 flex items-center justify-center shadow-xl shadow-orange-500/25">
                <Building2 className="w-8 h-8 text-white" />
              </div>
              <div className="flex-1">
                <h3 className="text-xl font-semibold mb-2">Contact Us</h3>
                <p className="text-gray-400 text-sm mb-4">
                  ApexNeural Private Limited<br />
                  5th Floor, Shantha Sriram Building, PRS Towers,<br />
                  Gachibowli, K.V. Rangareddy, Telangana - 500032
                </p>
                <a 
                  href="mailto:info@apexneural.com" 
                  className="inline-flex items-center gap-2 text-orange-400 hover:text-orange-300 transition-colors"
                >
                  <Mail className="w-4 h-4" />
                  info@apexneural.com
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
